apiVersion: v1
kind: Namespace
metadata:
  name: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong
  namespace: server
spec:
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
        - name: pong
          image: ko://dns/cmd/server
          ports:
          - containerPort: 8080
            name: tcp
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pong
  namespace: server
  labels:
    app: pong
spec:
  selector:
    app: pong
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: tcp
