apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    serving.knative.dev/creator: kubernetes-admin
    serving.knative.dev/lastModifier: kubernetes-admin
  creationTimestamp: "2022-08-31T18:55:36Z"
  generation: 1
  name: hello
  namespace: default
  resourceVersion: "1354"
  uid: 109fb18b-c336-4192-833b-61f5623f2230
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/updateTimestamp: "2022-08-31T18:55:36Z"
        client.knative.dev/user-image: gcr.io/knative-samples/helloworld-go
      creationTimestamp: null
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: TARGET
          value: World
        image: gcr.io/knative-samples/helloworld-go
        name: user-container
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: http://hello.default.svc.cluster.local
  conditions:
  - lastTransitionTime: "2022-08-31T18:55:52Z"
    status: "True"
    type: ConfigurationsReady
  - lastTransitionTime: "2022-08-31T18:55:52Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-08-31T18:55:52Z"
    status: "True"
    type: RoutesReady
  latestCreatedRevisionName: hello-00001
  latestReadyRevisionName: hello-00001
  observedGeneration: 1
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: hello-00001
  url: http://hello.default.example.com
