apiVersion: v1
items:
- apiVersion: serving.knative.dev/v1
  kind: Revision
  metadata:
    annotations:
      client.knative.dev/updateTimestamp: "2022-08-31T18:55:36Z"
      client.knative.dev/user-image: gcr.io/knative-samples/helloworld-go
      serving.knative.dev/creator: kubernetes-admin
      serving.knative.dev/routes: hello
      serving.knative.dev/routingStateModified: "2022-08-31T18:55:36Z"
    creationTimestamp: "2022-08-31T18:55:36Z"
    generation: 1
    labels:
      serving.knative.dev/configuration: hello
      serving.knative.dev/configurationGeneration: "1"
      serving.knative.dev/configurationUID: 51f041d8-71fd-41c3-adcc-b900dcfcf800
      serving.knative.dev/routingState: active
      serving.knative.dev/service: hello
      serving.knative.dev/serviceUID: 109fb18b-c336-4192-833b-61f5623f2230
    name: hello-00001
    namespace: default
    ownerReferences:
    - apiVersion: serving.knative.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: Configuration
      name: hello
      uid: 51f041d8-71fd-41c3-adcc-b900dcfcf800
    resourceVersion: "1583"
    uid: 126e685c-bd5b-4006-b8c0-44877229c9fc
  spec:
    containerConcurrency: 0
    containers:
    - env:
      - name: TARGET
        value: World
      image: gcr.io/knative-samples/helloworld-go
      name: user-container
      ports:
      - containerPort: 8080
        protocol: TCP
      readinessProbe:
        successThreshold: 1
        tcpSocket:
          port: 0
      resources: {}
    enableServiceLinks: false
    timeoutSeconds: 300
  status:
    actualReplicas: 0
    conditions:
    - lastTransitionTime: "2022-08-31T18:56:52Z"
      message: The target is not receiving traffic.
      reason: NoTraffic
      severity: Info
      status: "False"
      type: Active
    - lastTransitionTime: "2022-08-31T18:55:52Z"
      status: "True"
      type: ContainerHealthy
    - lastTransitionTime: "2022-08-31T18:55:52Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2022-08-31T18:55:52Z"
      status: "True"
      type: ResourcesAvailable
    containerStatuses:
    - imageDigest: gcr.io/knative-samples/helloworld-go@sha256:5ea96ba4b872685ff4ddb5cd8d1a97ec18c18fae79ee8df0d29f446c5efe5f50
      name: user-container
    desiredReplicas: 0
    observedGeneration: 1
kind: List
metadata:
  resourceVersion: ""
