apiVersion: v1
kind: Service
metadata:
  name: syncer
  namespace: kcp-syncer-localcluster-77q5enwy
  labels:
    app: kcp-syncer-localcluster-77q5enwy
spec:
  selector:
    app: kcp-syncer-localcluster-77q5enwy
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53
      name: tcp
    - protocol: UDP
      port: 53
      targetPort: 53
      name: upp
