apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: default
spec:
  containers:
    - name: dnsutils
      image: k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
  dnsConfig:
    nameservers:
      - 10.96.250.97
    options:
      - name: ndots
        value: "5"
    searches:
      - kourier-system.svc.cluster.local
      - svc.cluster.local
      - cluster.local
  dnsPolicy: None
  restartPolicy: Always
